#!/bin/bash
path_to_log=$1 # Path to the log file
top_5_ip_addresses=$( awk '{print $1}' ${path_to_log} | sort | uniq -c | sort -n | tail -n5 )
printf "\n\n"
printf "Top 5 IP addresses with the most requests:\n"
printf "${top_5_ip_addresses}" | awk '{print $2 " - " $1 " requests"}'
