#!/bin/bash
path_to_log=$1 # Path to the log file
top_5_ip_addresses=$( awk '{print $1}' ${path_to_log} | sort | uniq -c | sort -n | tail -n5 )
top_5_requested_paths=$(awk '{print $7}' ${path_to_log} | grep -E --no-messages '.*[^"]' | sort | uniq -c | sort -n | tail -n5)
printf "\n\n"
printf "Top 5 IP addresses with the most requests:\n"
printf "${top_5_ip_addresses}" | awk '{print $2 " - " $1 " requests"}'


printf "\n---\n\n"

printf "Top 5 most requested paths:\n"
printf '%s' "${top_5_requested_paths}" | awk '{print $2 " - " $1 " requests"}'

printf "\n---\n\n"
